# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build  ASP.Net Core app for n2k-portal-backend Staging

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    environment: Staging

    steps:
      - uses: actions/checkout@v4
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: copy config
        run: |
          copy natura2000_portal_back/Configs/appsettings_stg.json natura2000_portal_back/appsettings.json  
          del natura2000_portal_back/Configs/*.json
          rmdir natura2000_portal_back/Configs

      - name: dotnet publish
        shell: pwsh
        run: |
          $publishDir = "C:\Users\runneradmin\AppData\Local\Microsoft\dotnet/myapp"
          # Publish project
          dotnet publish -c Release --property:PublishDir=$publishDir

          # Create multi-line .env file
          @"
          BackboneDB_ConnectionString=${{ secrets.BACKBONEDB_CONNECTIONSTRING }}
          ReleasesDB_ConnectionString=${{ secrets.RELEASESDB_CONNECTIONSTRING }}
          FME_TOKEN=${{ secrets.FME_TOKEN }}
          "@ | Out-File -FilePath "$publishDir\env" -Encoding utf8                

      - name: Upload artifact for deployment job in Staging
        uses: actions/upload-artifact@v4
        with:
          name: backend-app_staging
          path: C:\Users\runneradmin\AppData\Local\Microsoft\dotnet/myapp
