# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - n2k-portal-backend

on:
  push:
    branches:
      - Development
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      BackboneDB_ConnectionString: ${{ secrets.DEV_BACKBONEDB_CONNECTIONSTRING }}
      ReleasesDB_ConnectionString: ${{ secrets.DEV_RELEASESDB_CONNECTIONSTRING }}
      FME_TOKEN: ${{ secrets.DEV_FME_TOKEN }}
      
    steps:
      - uses: actions/checkout@v4
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release
        
      - name: copy config
        run: |
          copy natura2000_portal_back/Configs/appsettings_dev.json natura2000_portal_back/appsettings.json  
          del natura2000_portal_back/Configs/*.json
          rmdir natura2000_portal_back/Configs

      - name: Create .env file
        shell: pwsh
        run: |
          # Ensure folder exists
          New-Item -ItemType Directory -Force -Path natura2000_portal_back | Out-Null
      
          # Create multi-line .env file
          @"
          BackboneDB_ConnectionString=aaaa
          ReleasesDB_ConnectionString=bbb
          FME_TOKEN=${{ secrets.DEV_FME_TOKEN }}
          "@ | Out-File -FilePath natura2000_portal_back\.env -Encoding utf8

      - name: Upload .env file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: portal-env
          path: natura2000_portal_back/.env
          
      - name: dotnet publish
        run: dotnet publish -c Release --property:PublishDir=C:\Users\runneradmin\AppData\Local\Microsoft\dotnet/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: C:\Users\runneradmin\AppData\Local\Microsoft\dotnet/myapp
  




